#!/bin/sh

shellinaboxd \
	--background="`dirname $0`/shellinaboxd.pid" \
	--localhost-only \
	--no-beep \
	--disable-ssl \
	--port=4101 \
	--css=css/shellinabox.css \
	--service /:$USER:$USER:HOME:"vi $PWD/index.html"
